const seedUserData = [
  { username: "AaravSharma", password: "P@ssword123!" },
  { username: "IshaanVerma", password: "Strong#456Pwd" },
  { username: "VihaanPatel", password: "SecUre789$Code" },
  { username: "AnanyaGupta", password: "C0mpl3xP@ssw0rd" },
  { username: "MeeraJoshi", password: "MyPa$$w0rd#2023" },
  { username: "RiyaKumar", password: "T0ugh&Key%987" },
  { username: "KabirSingh", password: "Safe!Acc0unt*123" },
  { username: "AditiNair", password: "U1tra@Secret#PWD" },
  { username: "KrishnaDas", password: "Hard2Break!2024" },
  { username: "PriyaReddy", password: "Secure$Login*ABC" },
  { username: "RahulMehta", password: "P@ssw0rd#789X" },
  { username: "SnehaBansal", password: "P@$$word2024!" },
  { username: "VikramMalhotra", password: "R0bust@Pass#321" },
  { username: "NishaSharma", password: "T1ght&Key%999" },
  { username: "ArjunRao", password: "W!nter123@S3cret" },
  { username: "PoojaIyer", password: "C0mpl3xP@ss#456" },
  { username: "RajivKapoor", password: "Lock&Safe@2023" },
  { username: "TanviSingh", password: "Secure!A@lpha1" },
  { username: "VanyaJain", password: "E@sy2R3m3mb3r!" },
  { username: "DevPatel", password: "H@rdP@$$1!" },
  { username: "KaranGill", password: "Key2&Strong#PWD" },
  { username: "NidhiChopra", password: "Br1ght!L0ck#2024" },
  { username: "RohanKhan", password: "S3cur3#Alpha@42" },
  { username: "AliaRoy", password: "Pa$$word!#Safe98" },
  { username: "SiddharthDas", password: "Tough#P@ss1234" },
  { username: "AnkitaVerma", password: "S@f3M3th0d%456" },
  { username: "KavyaShah", password: "H@rd2Crack!Key" },
  { username: "RitikaJain", password: "P@ss%Secure&2025" },
  { username: "AryanMishra", password: "R0ck$Lock@12345" },
];

export default seedUserData;
