const seedUserData = [
  {
    username: "AaravSharma",
    password: "P@ssword123!",
    name: "Aarav Sharma",
    location: "Delhi, India",
    interests: ["Technology", "Gaming", "Travel"],
    bio: "Tech enthusiast who loves exploring new gadgets and gaming.",
  },
  {
    username: "IshaanVerma",
    password: "Strong#456Pwd",
    name: "Ishaan Verma",
    location: "Mumbai, India",
    interests: ["Photography", "Movies", "Music"],
    bio: "Avid photographer capturing moments that tell stories.",
  },
  {
    username: "VihaanPatel",
    password: "SecUre789$Code",
    name: "Vihaan Patel",
    location: "Ahmedabad, India",
    interests: ["Coding", "AI", "Startups"],
    bio: "Full-stack developer passionate about AI and innovation.",
  },
  {
    username: "AnanyaGupta",
    password: "C0mpl3xP@ssw0rd",
    name: "Ananya Gupta",
    location: "Bangalore, India",
    interests: ["Art", "Design", "Writing"],
    bio: "Creative designer with a love for storytelling and visuals.",
  },
  {
    username: "MeeraJoshi",
    password: "MyPa$$w0rd#2023",
    name: "Meera Joshi",
    location: "Pune, India",
    interests: ["Cooking", "Yoga", "Reading"],
    bio: "Food lover and bookworm with a knack for mindfulness.",
  },
  {
    username: "RiyaKumar",
    password: "T0ugh&Key%987",
    name: "Riya Kumar",
    location: "Chennai, India",
    interests: ["Music", "Dance", "Fitness"],
    bio: "Fitness enthusiast who finds joy in music and movement.",
  },
  {
    username: "KabirSingh",
    password: "Safe!Acc0unt*123",
    name: "Kabir Singh",
    location: "Hyderabad, India",
    interests: ["Sports", "Adventure", "Technology"],
    bio: "Sports fanatic who loves adrenaline and tech advancements.",
  },
  {
    username: "AditiNair",
    password: "U1tra@Secret#PWD",
    name: "Aditi Nair",
    location: "Kochi, India",
    interests: ["Travel", "Photography", "Culture"],
    bio: "Globetrotter capturing the beauty of different cultures.",
  },
  {
    username: "KrishnaDas",
    password: "Hard2Break!2024",
    name: "Krishna Das",
    location: "Kolkata, India",
    interests: ["History", "Literature", "Politics"],
    bio: "History buff who enjoys unraveling the past through books.",
  },
  {
    username: "PriyaReddy",
    password: "Secure$Login*ABC",
    name: "Priya Reddy",
    location: "Visakhapatnam, India",
    interests: ["Gardening", "Movies", "Fitness"],
    bio: "Nature lover and movie enthusiast finding balance in life.",
  },
  {
    username: "RahulMehta",
    password: "P@ssw0rd#789X",
    name: "Rahul Mehta",
    location: "Jaipur, India",
    interests: ["Programming", "Gaming", "Podcasts"],
    bio: "Code geek who finds solace in games and inspiring podcasts.",
  },
  {
    username: "SnehaBansal",
    password: "P@$$word2024!",
    name: "Sneha Bansal",
    location: "Lucknow, India",
    interests: ["Painting", "Travel", "Cooking"],
    bio: "Artistic soul with a love for travel and culinary experiments.",
  },
  {
    username: "VikramMalhotra",
    password: "R0bust@Pass#321",
    name: "Vikram Malhotra",
    location: "Chandigarh, India",
    interests: ["Startups", "Leadership", "Networking"],
    bio: "Entrepreneurial spirit with a passion for innovation.",
  },
  {
    username: "NishaSharma",
    password: "T1ght&Key%999",
    name: "Nisha Sharma",
    location: "Indore, India",
    interests: ["Fitness", "Meditation", "Books"],
    bio: "Wellness advocate who loves staying fit and mindful.",
  },
  {
    username: "ArjunRao",
    password: "W!nter123@S3cret",
    name: "Arjun Rao",
    location: "Nagpur, India",
    interests: ["Gaming", "Movies", "Sports"],
    bio: "Competitive gamer and movie aficionado with a sporty side.",
  },
  {
    username: "PoojaIyer",
    password: "C0mpl3xP@ss#456",
    name: "Pooja Iyer",
    location: "Coimbatore, India",
    interests: ["Technology", "Coding", "Startups"],
    bio: "Tech-driven coder aiming to change the world with innovation.",
  },
  {
    username: "RajivKapoor",
    password: "Lock&Safe@2023",
    name: "Rajiv Kapoor",
    location: "Delhi, India",
    interests: ["Photography", "Music", "Adventure"],
    bio: "Explorer at heart capturing moments through the lens.",
  },
  {
    username: "TanviSingh",
    password: "Secure!A@lpha1",
    name: "Tanvi Singh",
    location: "Pune, India",
    interests: ["Yoga", "Cooking", "Writing"],
    bio: "Health-conscious foodie with a love for storytelling.",
  },
  {
    username: "VanyaJain",
    password: "E@sy2R3m3mb3r!",
    name: "Vanya Jain",
    location: "Bhopal, India",
    interests: ["Blogging", "Fitness", "Reading"],
    bio: "Writer and fitness enthusiast sharing stories with the world.",
  },
  {
    username: "DevPatel",
    password: "H@rdP@$$1!",
    name: "Dev Patel",
    location: "Ahmedabad, India",
    interests: ["Gaming", "Coding", "AI"],
    bio: "Gaming enthusiast with a knack for AI-powered solutions.",
  },
];

export default seedUserData;
